### PR TITLE
chore: remove stage2 for @babel/corev7.0.0-beta.55+

### PR DESCRIPTION
**Pull request by ahungrynoob**
## Checklist

* [x] `npm test` passes
* [ ] tests are included
* [ ] documentation is changed or added
* [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by ahungrynoob** [comment]
#114

**Comment by ahungrynoob** [comment]
如果ts-loader依赖的jsx配置项为preserve，还是需要Babel-preset-beidou-client的，我等会儿把依赖加到package.json，然后贴上tsconfig~

**Comment by ahungrynoob** [comment]
fixed #108

**Comment by njugray** [comment]
示例代码 和 bugfix 的 PR 分开提吧 @ahungrynoob

**Pull request merged**
